default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "root"
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: arcanegra_dev

test:
  <<: *default
  database: arcanegra_test

production:
  <<: *default
  database: arcanegra_dev
  username: root
  password: <%= ENV['ARCANEGRA_DATABASE_PASSWORD'] %>
