# default: &default
# development:
#   adapter: mysql2
#   encoding: utf8
#   database: arcanegra_dev
#   username: root
#   password: "root"
#
#   socket: /var/run/mysqld/mysqld.sock
#
# test:
#   adapter: mysql2
#   encoding: utf8
#   database: arcanegra_test
#   pool: 5
#   username: root
#   password: "root"
#
#   socket: /var/run/mysqld/mysqld.sock
#
# production:
#   adapter: mysql2
#   encoding: utf8
#   database: arcanegra
#   pool: 5
#   username: root
#   password: "root"
#   socket: /var/run/mysqld/mysqld.sock

## the rial
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "root"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: arcanegra_dev

test:
  <<: *default
  database: arcanegra_test

production:
  <<: *default
  database: arcanegra_dev
  username: root
  password: <%= ENV['ARCANEGRA_DATABASE_PASSWORD'] %>
